package models

// Game ID constants
const (
	// Item types
	ItemTypeSword     = 1
	ItemTypeDagger    = 2
	ItemTypeBow       = 3
	ItemTypeStaff     = 4
	ItemTypeWand      = 5
	ItemTypeSpell     = 6
	ItemTypeSeal      = 7
	ItemTypeCloak     = 8
	ItemTypeRobe      = 9
	ItemTypeLeather   = 10
	ItemTypeArmor     = 11
	ItemTypeWand2     = 12
	ItemTypeRing      = 13
	ItemTypePotion    = 14
	ItemTypeSprite    = 15
	ItemTypePet       = 16
	ItemTypeEgg       = 17
	ItemTypeTrap      = 18
	ItemTypeOrb       = 19
	ItemTypePrism     = 20
	ItemTypeScepter   = 21
	ItemTypeKatana    = 22
	ItemTypeShuriken  = 23
	ItemTypeWakizashi = 24

	// Container types
	ContainerTypeInventory     = 0
	ContainerTypeBackpack      = 1
	ContainerTypeVault         = 2
	ContainerTypeGiftChest     = 3
	ContainerTypePotionStorage = 4

	// Map IDs
	MapIDNexus     = 1
	MapIDVault     = 2
	MapIDGuildHall = 3
	MapIDRealm     = 4
	MapIDTutorial  = 5
	MapIDTest      = 6

	// Status effect IDs
	StatusEffectNOTHING           = 0
	StatusEffectDEAD              = 1
	StatusEffectQUIET             = 2
	StatusEffectWEAK              = 3
	StatusEffectSLOWED            = 4
	StatusEffectSICK              = 5
	StatusEffectDAZED             = 6
	StatusEffectSTUNNED           = 7
	StatusEffectBLIND             = 8
	StatusEffectHALLUCINATING     = 9
	StatusEffectDRUNK             = 10
	StatusEffectCONFUSED          = 11
	StatusEffectSTUNIMMUNE        = 12
	StatusEffectINVISIBLE         = 13
	StatusEffectPARALYZED         = 14
	StatusEffectSPEEDY            = 15
	StatusEffectBLEEDING          = 16
	StatusEffectARMORBROKENIMMUNE = 17
	StatusEffectHEALING           = 18
	StatusEffectDAMAGING          = 19
	StatusEffectBERSERK           = 20
	StatusEffectPAUSED            = 21
	StatusEffectSTASIS            = 22
	StatusEffectSTASISIMMUNE      = 23
	StatusEffectINVINCIBLE        = 24
	StatusEffectINVULNERABLE      = 25
	StatusEffectARMORED           = 26
	StatusEffectARMORBROKEN       = 27
	StatusEffectHEXED             = 28
	StatusEffectNINJASPEEDY       = 29
	StatusEffectUNSTABLE          = 30
	StatusEffectDARKNESS          = 31
	StatusEffectSLOWEDIMMUNE      = 32
	StatusEffectDAZEDIMMUNE       = 33
	StatusEffectPARALYZEDIMMUNE   = 34
	StatusEffectPETRIFIED         = 35
	StatusEffectPETRIFIEDIMMUNE   = 36
	StatusEffectPETEFFECTICON     = 37
	StatusEffectCURSE             = 38
	StatusEffectCURSEIMMUNE       = 39
	StatusEffectHPBOOST           = 40
	StatusEffectMPBOOST           = 41
	StatusEffectATTBOOST          = 42
	StatusEffectDEFBOOST          = 43
	StatusEffectSPDBOOST          = 44
	StatusEffectVITBOOST          = 45
	StatusEffectWISBOOST          = 46
	StatusEffectDEXBOOST          = 47
	StatusEffectSILENCED          = 48
	StatusEffectEXPOSED           = 49
	StatusEffectENERGIZED         = 50
	StatusEffectHPDEBUFF          = 51
	StatusEffectMPDEBUFF          = 52
	StatusEffectATTDEBUFF         = 53
	StatusEffectDEFDEBUFF         = 54
	StatusEffectSPDDEBUFF         = 55
	StatusEffectVITDEBUFF         = 56
	StatusEffectWISDEBUFF         = 57
	StatusEffectDEXDEBUFF         = 58
	StatusEffectINSPIRED          = 59
	StatusEffectGROUNDDAMAGE      = 99
)
